### ISSUE TITLE
FileClerk works only on localhost

### ISSUE THREAD

**Issue by mindmergedesign** [plainlanguage/Statamic-File-Clerk#5]
FileClerk works only from my development machine on localhost. When I push my site to staging and production servers, FileClerk doesn't work. I cannot upload files/images and I cannot choose any existing file from my Amazon bucket. 

See attachments for JS errors in console.

<img width="1042" alt="screen shot 2015-08-27 at 10 00 29 pm" src="https://cloud.githubusercontent.com/assets/571529/9537517/4dd703ba-4d07-11e5-880b-5cc9ab11f385.png">
<img width="1055" alt="screen shot 2015-08-27 at 10 01 45 pm" src="https://cloud.githubusercontent.com/assets/571529/9537518/4dd90f98-4d07-11e5-87f3-01d71ef53b4c.png">

**Comment by chadclark** [comment]
What PHP version are you running in each environment?

**Comment by mindmergedesign** [comment]
I am running PHP 5.4.42 on localhost using MAMP and PHP 5.4.33 on Staging and Production servers.

**Comment by mindmergedesign** [comment]
I updated my servers to PHP 5.5.28 and still having the issue.

**Comment by chadclark** [comment]
Can you share your settings for `_config/add-ons/fileclerk/fileclerk.yaml`?

**Comment by mindmergedesign** [comment]
.# Your AWS Access Key
aws_access_key: MYAWSACCESSKEY

.# Your AWS Secret Key
aws_secret_key: MyAwsSecretKey

.# Custom AWS Domain? (CNAME). Leave this empty if you are not using a custom domain. Do not include http:// or trailing slash.
custom_domain:

.# The name of the S3 Bucket. Do not include trailing slash.
bucket: mmdimages

.# The folder/path to upload the file. Leave empty if uploading into bucket root.
.# For nested directories, separate with a /, path/to/directory
directory: klm

.# Define the file types that can be uploaded. [array] Not required.
content_types: [jpg, jpeg, gif, png]

.# Access for the uploaded file. Required.
.# Options include:
.# - private
.# - public-read
.# - public-read-write
.# - authenticated-read
permissions: public-read

.# Cache-control
cache-control:

**Comment by mindmergedesign** [comment]
I think I found the issue. It seems that my servers were blocking Amazon S3 for whatever reason. I had to clear the deny entries in the firewall to whitelist Amazon's IP. Thanks for all the help.

**Comment by chadclark** [comment]
Ah, that makes sense. Glad you got it sorted out!
